"""Export the RDNA4 factored-LSTM layer kernels as HSACO + C headers (per arch).

Two kernels (mirrors cute/ampere/factored_lstm/export_factored_lstm_i8.py, and slorado's
CRFModel.cpp use):
  1. fp8 down-projection  hh_down = h_fp8 @ dn_fp8^T  (fp8 -> f16) — the base preshuffle GEMM.
  2. fused factored-LSTM step (f16 up-projections into 4 gate accumulators + gates + cell
     update + int8 hidden output at fixed 1/127).

Run:
    <venv>/bin/python fly/rdna4/factored_lstm/export_fp8_factored_lstm.py            # all RDNA4 archs
    <venv>/bin/python fly/rdna4/factored_lstm/export_fp8_factored_lstm.py --arch gfx1201

Outputs (per arch, in artifacts/<gfxNNNN>/):
    factored_lstm_fp8_H{H}_Khh{K_hh}_R{R}.hsaco + .h   (fused step, 11-arg wrapper)
    down_proj_fp8_R{R}_K{H}.hsaco + .h                 (fp8 down-proj, 5-arg GEMM wrapper)
"""
import argparse
import os
import sys

os.environ.setdefault("FLYDSL_RUNTIME_ENABLE_CACHE", "0")

import torch

_HERE = os.path.dirname(os.path.abspath(__file__))          # fly/rdna4/factored_lstm
_RDNA4 = os.path.dirname(_HERE)                             # fly/rdna4
sys.path.insert(0, _HERE)
sys.path.insert(0, _RDNA4)
sys.path.insert(0, os.path.join(_RDNA4, "gemm"))            # base preshuffle GEMM (down-proj)
from rdna_fp8_factored_lstm import compile_fp8_factored_lstm
from rdna_fp8_preshuffle_gemm import compile_fp8_gemm
import _fp8_export as fe

# Layer shape (mirrors the CUDA config). B (M) sizes the symbolic trace only (dynamic at runtime).
CONFIG = dict(H=1024, K_hh=128, R=128, B=128)
STEP_TILE_M, STEP_TILE_N = 32, 32   # must match compile_fp8_factored_lstm defaults
STEP_THREADS = 32


# ── fused step: compile + header ──────────────────────────────────────────────

def _compile_step_ir(H, K_hh, R, B):
    Kc = K_hh + R
    launcher = compile_fp8_factored_lstm(H=H, K_hh=K_hh, R=R)
    h_out = torch.zeros(B, H, dtype=torch.int8).cuda()
    cell = torch.zeros(B, H, dtype=torch.float32).cuda()
    A = torch.zeros(B, Kc, dtype=torch.float16).cuda()
    Bx = [torch.zeros(H, Kc, dtype=torch.float16).cuda() for _ in range(4)]
    bias = [torch.zeros(H, dtype=torch.float32).cuda() for _ in range(4)]
    try:
        launcher(h_out, cell, A, *Bx, *bias, B, torch.cuda.current_stream())
        torch.cuda.synchronize()
    except Exception:
        pass
    arts = list(launcher._mem_cache.values())
    if not arts:
        raise RuntimeError("_mem_cache empty after factored-LSTM step compile")
    return arts[0]._ir_text


_STEP_HEADER = """\
/* Auto-generated by export_fp8_factored_lstm.py — do not edit.
 *
 * HSACO ELF for {kernel_name} (RDNA4 wave32).
 *
 * Fused factored-LSTM step. f16 K-merged up-projections into 4 gate accumulators, gates,
 * cell update (f32 in place), int8 hidden output (fixed scale 1/127; h in [-1,1]).
 *
 * Fixed dims: H={H}, K_hh={K_hh}, R={R}, Kc={Kc}
 *   h_out:  int8  [M, {H}]     hidden output (dequant: *(1/127))
 *   cell:   f32   [M, {H}]     cell state, read + written in place
 *   A:      f16   [M, {Kc}]    concat(hh_down | x_down)
 *   B_i/f/g/o: f16 [{H}, {Kc}] per-gate weight concat(up_hh | up_ih)
 *   bias_i/f/g/o: f32 [{H}]
 *
 * M must be a runtime multiple of tile_m={tile_m}.
 * Grid: (M/{tile_m}) * {grid_n} x 1 x 1   Block: {threads} x 1 x 1
 */
#pragma once
#include <hip/hip_runtime.h>
#include <stdint.h>
#include <stdio.h>

#define FACTORED_LSTM_FP8_H        {H}
#define FACTORED_LSTM_FP8_KC       {Kc}
#define FACTORED_LSTM_FP8_TILE_M   {tile_m}
#define FACTORED_LSTM_FP8_TILE_N   {tile_n}
#define FACTORED_LSTM_FP8_THREADS  {threads}

typedef struct {{
    hipModule_t   module;
    hipFunction_t func;
}} factored_lstm_fp8_Module_t;

static inline int factored_lstm_fp8_Module_Load(factored_lstm_fp8_Module_t *m, const char *hsaco_path) {{
    hipError_t err = hipModuleLoad(&m->module, hsaco_path);
    if (err != hipSuccess) {{
        fprintf(stderr, "factored_lstm_fp8: hipModuleLoad(%s): %s\\n", hsaco_path, hipGetErrorString(err));
        return (int)err;
    }}
    err = hipModuleGetFunction(&m->func, m->module, "{kernel_name}");
    if (err != hipSuccess) {{
        fprintf(stderr, "factored_lstm_fp8: hipModuleGetFunction: %s\\n", hipGetErrorString(err));
        (void)hipModuleUnload(m->module);
        return (int)err;
    }}
    return 0;
}}

static inline void factored_lstm_fp8_Module_Unload(factored_lstm_fp8_Module_t *m) {{
    if (m->module) (void)hipModuleUnload(m->module);
    m->module = NULL; m->func = NULL;
}}

/* Launch the fused factored-LSTM step. M is a runtime multiple of FACTORED_LSTM_FP8_TILE_M. */
static inline int factored_lstm_fp8_wrapper(
        const factored_lstm_fp8_Module_t *m,
        hipDeviceptr_t d_h_out,   /* int8 [M,{H}] */
        hipDeviceptr_t d_cell,    /* f32  [M,{H}] in/out */
        hipDeviceptr_t d_A,       /* f16  [M,{Kc}] */
        hipDeviceptr_t d_B_i, hipDeviceptr_t d_B_f, hipDeviceptr_t d_B_g, hipDeviceptr_t d_B_o,  /* f16 [{H},{Kc}] */
        hipDeviceptr_t d_bias_i, hipDeviceptr_t d_bias_f, hipDeviceptr_t d_bias_g, hipDeviceptr_t d_bias_o,  /* f32 [{H}] */
        int32_t M,
        hipStream_t stream) {{
    if (M % FACTORED_LSTM_FP8_TILE_M != 0) {{
        fprintf(stderr, "factored_lstm_fp8: M=%d not divisible by tile_m=%d\\n", M, FACTORED_LSTM_FP8_TILE_M);
        return -1;
    }}
    int32_t grid_m = M / FACTORED_LSTM_FP8_TILE_M;
    unsigned int total_blocks = (unsigned int)grid_m * ({H} / FACTORED_LSTM_FP8_TILE_N);
    void *args[] = {{ &d_h_out, &d_cell, &d_A, &d_B_i, &d_B_f, &d_B_g, &d_B_o,
                     &d_bias_i, &d_bias_f, &d_bias_g, &d_bias_o, &grid_m }};
    hipError_t err = hipModuleLaunchKernel(m->func, total_blocks, 1, 1,
            FACTORED_LSTM_FP8_THREADS, 1, 1, 0, stream, args, NULL);
    if (err != hipSuccess) {{
        fprintf(stderr, "factored_lstm_fp8: hipModuleLaunchKernel: %s\\n", hipGetErrorString(err));
        return (int)err;
    }}
    return 0;
}}
"""


def _export_step(cfg, artifacts_dir):
    H, K_hh, R, B = cfg["H"], cfg["K_hh"], cfg["R"], cfg["B"]
    Kc = K_hh + R
    name = f"factored_lstm_fp8_H{H}_Khh{K_hh}_R{R}"
    print(f"\n[step H={H} K_hh={K_hh} R={R}] -> {name}")
    ir = _compile_step_ir(H, K_hh, R, B)
    kname = fe.find_kernel_name(ir, "kernel_factored_lstm_0")
    hsaco = fe.extract_hsaco(ir)
    header = _STEP_HEADER.format(kernel_name=kname, H=H, K_hh=K_hh, R=R, Kc=Kc,
                                 tile_m=STEP_TILE_M, tile_n=STEP_TILE_N,
                                 threads=STEP_THREADS, grid_n=H // STEP_TILE_N)
    header += fe.module_loaddata_fn("factored_lstm_fp8", kname)
    fe.write_artifacts(artifacts_dir, name, hsaco, header)


# ── fp8 down-projection (base preshuffle GEMM, fp8 -> f16) ─────────────────────

def _compile_down_proj_ir(B, R, H):
    # down-proj: A = h_fp8 [B,H], B = dn_fp8 preshuffled [R,H], out f16 [B,R]. N=R, K=H.
    launcher = compile_fp8_gemm(M=B, N=R, K=H)
    C = torch.zeros(B, R, dtype=torch.float16).cuda()
    A = torch.zeros(B, H, dtype=torch.uint8).cuda()
    Bsh = torch.zeros(R // 16, H // 16, 2, 16, 8, dtype=torch.uint8).cuda()
    sa = torch.ones(B, dtype=torch.float32).cuda()
    sb = torch.ones(R, dtype=torch.float32).cuda()
    try:
        launcher(C, A, Bsh, sa, sb, torch.cuda.current_stream(), B)
        torch.cuda.synchronize()
    except Exception:
        pass
    arts = list(launcher._mem_cache.values())
    if not arts:
        raise RuntimeError("_mem_cache empty after down-proj compile")
    return arts[0]._ir_text


def _dp_config(B, R):
    tile_m = 64 if B >= 256 else 32
    tile_n = 256 if B >= 256 else 128
    return tile_m, min(tile_n, R)


_DP_HEADER = """\
/* Auto-generated by export_fp8_factored_lstm.py — do not edit.
 *
 * HSACO ELF for {kernel_name} (RDNA4 wave32).  fp8 down-projection: C[M,{N}] = A@B^T (fp8 -> f16),
 * per-token scale_a[M], per-channel scale_b[{N}]. B preshuffled [{N_div16},{K_div16},2,16,8].
 * Fixed dims: N=R={N}, K=H={K}.  M runtime multiple of tile_m={tile_m}.
 */
#pragma once
#include <hip/hip_runtime.h>
#include <stdint.h>
#include <stdio.h>

#define DOWN_PROJ_FP8_N        {N}
#define DOWN_PROJ_FP8_K        {K}
#define DOWN_PROJ_FP8_TILE_M   {tile_m}
#define DOWN_PROJ_FP8_TILE_N   {tile_n}
#define DOWN_PROJ_FP8_THREADS  {threads}

typedef struct {{ hipModule_t module; hipFunction_t func; }} down_proj_fp8_Module_t;

static inline int down_proj_fp8_Module_Load(down_proj_fp8_Module_t *m, const char *hsaco_path) {{
    hipError_t err = hipModuleLoad(&m->module, hsaco_path);
    if (err != hipSuccess) {{ fprintf(stderr, "down_proj_fp8: hipModuleLoad: %s\\n", hipGetErrorString(err)); return (int)err; }}
    err = hipModuleGetFunction(&m->func, m->module, "{kernel_name}");
    if (err != hipSuccess) {{ fprintf(stderr, "down_proj_fp8: hipModuleGetFunction: %s\\n", hipGetErrorString(err)); (void)hipModuleUnload(m->module); return (int)err; }}
    return 0;
}}
static inline void down_proj_fp8_Module_Unload(down_proj_fp8_Module_t *m) {{
    if (m->module) (void)hipModuleUnload(m->module); m->module = NULL; m->func = NULL;
}}
static inline int down_proj_fp8_wrapper(
        const down_proj_fp8_Module_t *m,
        hipDeviceptr_t d_C, hipDeviceptr_t d_A, hipDeviceptr_t d_B_shuf,
        hipDeviceptr_t d_scale_a, hipDeviceptr_t d_scale_b, int32_t M, hipStream_t stream) {{
    if (M % DOWN_PROJ_FP8_TILE_M != 0) {{ fprintf(stderr, "down_proj_fp8: M=%d not div by %d\\n", M, DOWN_PROJ_FP8_TILE_M); return -1; }}
    int32_t grid_m = M / DOWN_PROJ_FP8_TILE_M;
    unsigned int total_blocks = (unsigned int)grid_m * ({N} / DOWN_PROJ_FP8_TILE_N);
    void *args[] = {{ &d_C, &d_A, &d_B_shuf, &d_scale_a, &d_scale_b, &grid_m }};
    hipError_t err = hipModuleLaunchKernel(m->func, total_blocks, 1, 1, DOWN_PROJ_FP8_THREADS, 1, 1, 0, stream, args, NULL);
    if (err != hipSuccess) {{ fprintf(stderr, "down_proj_fp8: launch: %s\\n", hipGetErrorString(err)); return (int)err; }}
    return 0;
}}
"""


def _export_down_proj(cfg, artifacts_dir):
    H, R, B = cfg["H"], cfg["R"], cfg["B"]
    tile_m, tile_n = _dp_config(B, R)
    # waves for THREADS: mirror _compute_config in the gemm export
    waves = 2 * 2 if (tile_m >= 64 and tile_n >= 128) else (1 * 2 if tile_n >= 256 else
            (2 if (tile_m >= 64 or tile_n >= 128) else 1))
    threads = waves * 32
    name = f"down_proj_fp8_R{R}_K{H}"
    print(f"\n[down-proj N=R={R} K=H={H}] -> {name}")
    ir = _compile_down_proj_ir(B, R, H)
    kname = fe.find_kernel_name(ir, "kernel_gemm_0")
    hsaco = fe.extract_hsaco(ir)
    header = _DP_HEADER.format(kernel_name=kname, N=R, K=H, N_div16=R // 16, K_div16=H // 16,
                               tile_m=tile_m, tile_n=tile_n, threads=threads)
    header += fe.module_loaddata_fn("down_proj_fp8", kname)
    fe.write_artifacts(artifacts_dir, name, hsaco, header)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--arch", action="append", help="RDNA4 arch(es) (default: %s)" % fe.RDNA4_ARCHS)
    args = ap.parse_args()
    for arch in (args.arch or fe.RDNA4_ARCHS):
        print(f"\n=== arch {arch} ===")
        fe.set_compile_arch(arch)
        compile_fp8_factored_lstm.cache_clear()
        compile_fp8_gemm.cache_clear()
        d = fe.artifacts_dir_for(arch)
        _export_step(CONFIG, d)
        _export_down_proj(CONFIG, d)
        print(f"Done -> {d}/")
